services:
  guacd:
    image: guacamole/guacd
    container_name: guacd
    restart: unless-stopped
    networks:
      - guacamole-net

  postgres:
    image: postgres:15
    container_name: guacamole-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: guacamole_password
    networks:
      - guacamole-net
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # One-time database initialization
  db-init:
    image: postgres:15
    depends_on:
      - postgres
    networks:
      - guacamole-net
    environment:
      PGPASSWORD: guacamole_password
    volumes:
      - ./initdb.sql:/initdb.sql:ro
    command: >
      bash -c "
        until pg_isready -h postgres -U guacamole_user; do
          echo 'Waiting for postgres...'
          sleep 2
        done
        echo 'PostgreSQL is ready. Running initialization...'
        psql -h postgres -U guacamole_user -d guacamole_db -f /initdb.sql
        echo 'Database initialized successfully!'
      "
    restart: "no"

  guacamole:
    image: guacamole/guacamole
    container_name: guacamole
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      GUACD_HOSTNAME: guacd
      GUACD_PORT: 4822
      POSTGRESQL_HOSTNAME: postgres
      POSTGRESQL_PORT: 5432
      POSTGRESQL_DATABASE: guacamole_db
      POSTGRESQL_USER: guacamole_user
      POSTGRESQL_PASSWORD: guacamole_password
    networks:
      - guacamole-net
    depends_on:
      - guacd
      - postgres
      - db-init

networks:
  guacamole-net:
    driver: bridge

volumes:
  postgres-data: